#!/usr/bin/env bash
# This script displays different messages based on the loop iteration and number

counter=1

while [ $counter -le 20 ]
do
  case $counter in
    4)
      echo "4 and bad luck from China"
      ;;
    9)
      echo "9 and bad luck from Japan"
      ;;
    17)
      echo "17 and bad luck from Italy"
      ;;
    *)
      echo "$counter"
      ;;
  esac

  counter=$((counter + 1))
done
